#!/usr/bin/env ruby

require 'json'
require 'jsonapi/serializable'

class SerializableArticle < JSONAPI::Serializable::Resource
  type :articles
end

class Article < OpenStruct; end

article = Article.new(id: 1)

renderer = JSONAPI::Serializable::SuccessRenderer.new
hash = renderer.render(article, jsonapi: {
                         version: "1.0",
                         meta: { compliant: "true" }
                       })
puts hash.to_json
