#!/usr/bin/env ruby

require 'json'
require 'jsonapi/serializable'

class SerializableArticle < JSONAPI::Serializable::Resource
  type :articles
end

class Article < OpenStruct; end

article = Article.new(id: 1)

renderer = JSONAPI::Serializable::SuccessRenderer.new
hash = renderer.render(article)
puts hash.to_json
